apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bigip2-ext
  namespace: f5-bigip
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "bigip2-ext", 
    "type": "ovn-k8s-cni-overlay",
    "topology": "localnet",
    "netAttachDefName": "f5-bigip/bigip2-ext",
    "vlanID": 3011,
    "ipam": {}
  }'

