apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: net-ha
  namespace: f5-bigip
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "net-ha", 
    "type": "ovn-k8s-cni-overlay",
    "topology": "localnet",
    "netAttachDefName": "f5-bigip/net-ha",
    "vlanID": 3012,
    "ipam": {}
  }'

