apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-vms
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  desiredState:
    interfaces:
    - name: ovs-vms
      type: ovs-bridge
      state: up
      bridge:
        allow-extra-patch-ports: true
        options:
          stp: true
        port:
          - name: eno1
    ovn:
      bridge-mappings:
      - localnet: bigip1-mgmt
        bridge: ovs-vms
        state: present
      - localnet: bigip1-ha
        bridge: ovs-vms
        state: present
      - localnet: bigip1-ext
        bridge: ovs-vms
        state: present
      - localnet: bigip1-int
        bridge: ovs-vms
        state: present
      - localnet: bigip2-mgmt
        bridge: ovs-vms
        state: present
      - localnet: bigip2-ha
        bridge: ovs-vms
        state: present
      - localnet: bigip2-ext
        bridge: ovs-vms 
        state: present
      - localnet: bigip2-int
        bridge: ovs-vms
        state: present

