apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bigip1-int
  namespace: f5-bigip
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "bigip1-int", 
    "type": "ovn-k8s-cni-overlay",
    "topology": "localnet",
    "netAttachDefName": "f5-bigip/bigip1-int",
    "vlanID": 3010,
    "ipam": {}
  }'

