apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: bigip2-datavolume
  namespace: f5-bigip
spec:
  source:
    http:
      url: "http://<server address>/BIGIP-17.1.1.2-0.0.10.qcow2"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 150Gi
